---
title: "working on functions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remotes::install_github("nhausmna/twelvedays")
library(stringr)
library(dplyr)
library(glue)
library(purrr)
```

```{r}
pluralize_gift <- function(gift){
  gift <- paste(gift, "s",  sep="")
  gift <- gift %>%
    str_replace("ys$", "ies") %>%
    str_replace("ooses$", "eese")

  return(gift)
}
```

```{r}
make_phrase <- function(num, num_word, item, verb, adjective, location){
  if(num == 1)
    return(glue("a {item} {location}."))
  item <- pluralize_gift(item)
  if(!is.na(verb))
    return(glue("{num_word} {item} {verb}"))
  if(!is.na(adjective))
    return(glue("{num_word} {adjective} {item}"))
  return(glue("{num_word} {item} {location}"))
}
```

```{r}
sing_day <- function(dataset, line, phrase_col){

  phrases <- dataset %>% pull({{phrase_col}})
  dayname <- dataset$Day.in.Words[line]
  toRet <- glue("On the {dayname} day of Christmas, my true love sent to me,")
  #????
  if(line ==1){
    get_line <- function(line){
      return (phrases[line])
    }
  }
  else{
    get_line <- function(line){
      if(line == 1)
        return(paste("and", phrases[line]))
      return (phrases[line])
    }
  }
  after_comma <- paste(rev(map_chr(1:line, get_line)), collapse=',\n' )
  return(paste(toRet, after_comma, sep = '\n'))
}
```

```{r}
xmas <- xmas %>%
  mutate(number_strings = c('one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve'))
xmas <- xmas %>%  
  mutate(
    Full.Phrase = pmap_chr(xmas, ~make_phrase(..1, 
                                              ..7, 
                                              ..3, 
                                              ..4, 
                                              ..5, 
                                              ..6))
  )
cat(sing_day(xmas, 1, Full.Phrase))
```


